kind: Pod
apiVersion: v1
metadata:
 name: env-pod
spec:
  containers:
    - name: nginx
      image: nginx
      env: ## setting environment variables to the container
        - name: course
          value: devSecops
        - name: trainer
          value: shiva
    - name : nginx-2
      image: nginx
      env:
        - name: field
          value: it-field
