kind: Pod
apiVersion: v1
metadata:
 name: env-pod
spec:
  conatiners:
    - name: nginx
      image: nginx
      env:
        - name: course
          value: devSecops
        - name: trainer
          value: shiva
