apiVersion: v1
kind: Pod
metadata:  
 name: config-map-demo
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom: # it takes from 09-config-map data as key value pairs
        - configMapRef:
            name: pod-config